// LangTranslate/translate_frontend_react/src/App.js
import React, {useState} from 'react';
import axios from 'axios';

function App(){
  const [originalText, setOriginalText]=useState('');
  const [translatedText, setTranslatedText]=useState('');

  const handleTranslate=async()=>{
    try{
      const response=await axios.post('http://127.0.0.1:8000/api/translate/', {
        originalText: originalText, 
      });
      setTranslatedText(response.data.translated_text);
    } catch(error){
      console.error('Error translating text: ', error);
    }
  };

  return (
    <div className="container mt-5">
      <h1 className="text-center mb-4">Language Translation App</h1>
      <div className="form-group">
        <label htmlFor="originalText">Original Text:</label>
        <textarea
          className="form-control"
          id="originalText"
          value={originalText}
          onChange={(e) => setOriginalText(e.target.value)}
        />
      </div>
      <div className="form-group mt-3">
        <button
          className="btn btn-primary"
          onClick={handleTranslate}
        >
          Translate
        </button>
      </div>
      {translatedText && (
        <div className="mt-4">
          <label>Translated Text:</label>
          <div className="alert alert-success" role="alert">
            {translatedText}
          </div>
        </div>
      )}
    </div>
  );
}

export default App;

// LangTranslate/translate_frontend_angular/src/app/app.component.ts
import { Component } from '@angular/core';
import {TranslateService} from './translate.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  originalText: string='';
  translatedText: string='';

  constructor(private translateService: TranslateService){}

  handleTranslate():void{
    this.translateService.translate(this.originalText).subscribe(
      (response: any) => {
        this.translatedText = response.translated_text;
      },
      (error: any) => {
        console.error('Error translating text:', error);
      }
    );
  }
}

<div class="container mt-5">
  <h1 class="text-center mb-4">
    Language Translation App
  </h1>
  <div class="form-group">
    <label for="originalText">
      OriginalText:
    </label>
    <textarea class="form-control" id="originalText" [(ngModel)]="originalText">
    </textarea>
  </div>
  <div class="form-group mt-3">
    <button class="btn btn-primary" (click)="handleTranslate()">
      Translate
    </button>
  </div>
  <div *ngIf="translatedText" class="mt-4">
    <label> Translated text:
    </label>
    <div class="alert alert-success" role="alert">
      {{translatedText}}
    </div>
  </div>
</div>
